use_frameworks!

platform :ios, '9.0'

target 'WallifeSDK_Example' do
  pod 'WallifeSDK', :path => '../'

  target 'WallifeSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
